---
# Identity API ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-api-config
  namespace: identity-system
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://*:80"
  AllowedHosts: "*"
  
  # JWT Configuration
  Jwt__Authority: "http://keycloak-service:8080/realms/fiap-cloud-games"
  Jwt__Audience: "fcg-api"
  
  # Keycloak Configuration  
  KeycloakConfiguration__BaseUrl: "http://keycloak-service:8080"
  KeycloakConfiguration__TokenEndpointPath: "/realms/master/protocol/openid-connect/token"
  KeycloakConfiguration__UsersEndpointPath: "/admin/realms/fiap-cloud-games/users"
  KeycloakConfiguration__TargetRealm: "fiap-cloud-games"
  KeycloakConfiguration__Audience: "http://keycloak-service:8080"
  KeycloakConfiguration__AdminClientId: "fcg-api-service-account"
  KeycloakConfiguration__ApiClientId: "fcg-api"

---
# Keycloak ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: identity-system
data:
  KC_DB: "postgres"
  KC_DB_URL_HOST: "keycloak-db-service"
  KC_DB_URL_DATABASE: "keycloak"
  KC_DB_URL_PORT: "5432"
  KC_DB_USERNAME: "keycloak"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: "true"

---
# Kong ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: identity-system
data:
  KONG_DATABASE: "postgres"
  KONG_PG_HOST: "kong-db-service"
  KONG_PG_DATABASE: "kong"
  KONG_PG_USER: "kong"
  KONG_PG_PASSWORD: "kong123"
  KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
  KONG_ADMIN_ERROR_LOG: "/dev/stderr"
  KONG_PROXY_ACCESS_LOG: "/dev/stdout"
  KONG_PROXY_ERROR_LOG: "/dev/stderr"
  KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
  KONG_ADMIN_GUI_LISTEN: "0.0.0.0:8002"
  KONG_ADMIN_GUI_URL: "http://kong-admin.fcg-identity.com"