---
# Identity API ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-api-config
  namespace: identity-system
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://*:80"
  AllowedHosts: "*"
  
  # JWT Configuration
  Jwt__Authority: "http://keycloak-service:8080/realms/fiap-cloud-games"
  Jwt__Audience: "fcg-api"
  
  # Keycloak Configuration  
  KeycloakConfiguration__BaseUrl: "http://keycloak-service:8080"
  KeycloakConfiguration__TokenEndpointPath: "/realms/master/protocol/openid-connect/token"
  KeycloakConfiguration__UsersEndpointPath: "/admin/realms/fiap-cloud-games/users"
  KeycloakConfiguration__TargetRealm: "fiap-cloud-games"
  KeycloakConfiguration__Audience: "http://keycloak-service:8080"
  KeycloakConfiguration__AdminClientId: "fcg-api-service-account"
  KeycloakConfiguration__ApiClientId: "fcg-api"

---
# Keycloak ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: identity-system
data:
  KC_DB: "postgres"
  KC_DB_URL_HOST: "keycloak-db-service"
  KC_DB_URL_DATABASE: "keycloak"
  KC_DB_URL_PORT: "5432"
  KC_DB_USERNAME: "keycloak"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: "true"

