apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-app
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge
  template:
    metadata:
      labels:
        app: tech-challenge
    spec:
      containers:
      - name: tech-challenge-container
        image: IMAGE_TAG_PLACEHOLDER
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: tech-challenge-configmap
        - secretRef:
            name: tech-challenge-secret